volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    build: ./backend/
    depends_on:
      - db
    env_file: ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  frontend:
    container_name: foodgram_frontend
    env_file: ./.env
    build: ./frontend/
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram_proxy
    image: nginx:1.25.4-alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend