"""Константы проекта."""

USER_NAMES_MAX_LENGTH = 80
USER_EMAIL_MAX_LENGTH = 128
USER_NICKNAME_MAX_LENGTH = 100
USER_REGEX_CONTROLLER = r"^[\w.@+-]+$"

PRODUCT_NAME_MAX_LENGTH = 64
MEASUREMENT_MAX_LENGTH = 16
RECIPE_MAX_NAME_LENGTH = 100
RECIPE_MIN_TIME = 1
INGREDIENT_MIN_AMOUNT = 1
