"""Константы проекта."""

USER_NAMES_MAX_LEN = 80
USER_EMAIL_MAX_LEN = 128
USER_NICKNAME_MAX_LEN = 100
USER_REGEX_CONTROLLER = r"^[\w.@+-]+$"
CONST_PAGES = 8

RECIPE_MIN_TIME = 1
RECIPE_MAX_TIME = 2880
RECIPE_NAME_MAX_LEN = 128
INGREDIENT_MIN_AMOUNT = 1
INGREDIENT_MAX_AMOUNT = 40
INGREDIENT_NAME_MAX_LEN = 256
MEASUREMENT_UNIT_MAX_LEN = 32
